---
apiVesion: v1
kind: Deployment
metadata:
  name: my-aru
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: ay-aru
  template:
    metadata:
      labels:
        app: my-aru
    spec:
      containers:
      - name: cont-1
        image: shaikmustafa/dm
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops
spec:
  type: NodePort
  selector:
    app: my-aru
  ports:
    - port: 8080
      targetPort: 80
      NodePort: 30975
